### ISSUE TITLE
Support having titles that are asynchronously generated based on `routeParams`

### ISSUE THREAD

**Issue by eternaleye** [vikejs/vike-react#23] opened 2023-09-28 22:57 UTC
I have a site where I have tutorials that are chosen by a route parameter, and I need the title to include the name of the tutorial. This requires that I:

1. Access the `pageContext`, and then the `routeParams`.
2. `await import` the appropriate tutorial (it's an AsciiDoc document).
3. Use the AsciiDoc parser on it, producing a data structure `doc`.
4. Use `doc.getDocumentTitle()` to extract the tutorial title.
5. Format it into my overall page title.

This is currently impossible with `vike-react`.

**Comment by brillout** [comment] 2023-09-29 08:11
You should be able to do it by 1. using the `onBeforeRender()` hook to process data, and 2. settting `title` to a function.

```js
// /pages/some-page/+title.js

export default (pageContext) => {
  // pageContext.data is provided by your onBeforeRender() hook
  return inferTtitle(pageContext.data)
}
```

Closing but let me know if you still run into issues and I'll re-open.

The DX isn't ideal right now mostly because of a lack of documentation. It's very much on the radar to improve things here.

**Comment by AurelienLourot** [comment] 2023-09-29 11:42
@eternaleye also it's possible without `+title` file, just directly in `onBeforeRender()`. See [this example](https://github.com/vikejs/vike-react/blob/main/examples/basic/pages/star-wars/%40id/%2BonBeforeRender.ts)

**Comment by brillout** [comment] 2023-09-29 11:46
(@AurelienLourot Btw. been thinking about it: I think the combo `+data.js` and `+title.js` could be neat after all. The idea here being that `pageContext.data` (i.e. whatever `+data.js` returns) is included in `passToClient` by default. This means that the `+title.js` function would always have access to `pageContext.data`.)

**Comment by eternaleye** [comment] 2023-10-03 22:24
@brillout

> You should be able to do it by 1. using the onBeforeRender() hook to process data, and 2. settting title to a function.

I cannot set title to a function, because of the following code in `getTitle.ts`:

https://github.com/vikejs/vike-react/blob/05da94135b8b75b95d1decbae29abe4fcea040ce/vike-react/renderer/getTitle.ts#L11-L13

@AurelienLourot 

> @eternaleye also it's possible without +title file, just directly in onBeforeRender(). See this example

I'll try that.

**Comment by brillout** [comment] 2023-10-04 09:27
This code snippet ensures that `pageContext.title` is a string: this is a different variable than `Config['title']`. 

> I cannot set `title` to a function

If that's the case then I consider it a bug: reproduction welcome.

**Comment by brillout** [comment] 2023-10-04 09:28
> settting `title` to a function.

I meant setting `+title.js` to a function.

**Comment by eternaleye** [comment] 2023-10-04 19:09
Yes, that is the exception thrown when I `export default` a function in `+title.ts`

**Comment by brillout** [comment] 2023-10-04 19:25
Let me see if I can reproduce.

**Comment by brillout** [comment] 2023-10-04 19:42
I cannot reproduce: 9a93058f4be3de32a166fc1ca7fcb2f5d15e41bd. Reproduction welcome.

**Closed by brillout** 2023-10-04 19:42 UTC
